### ISSUE TITLE
SeqSero WDL task/workflow needed

### ISSUE THREAD

**Issue by kevinlibuit** [theiagen/public_health_bacterial_genomics#11]

**Comment by kevinlibuit** [comment]
NextFlow process reference: https://github.com/StaPH-B/staphb_toolkit/blob/main/staphb_toolkit/workflows/tredegar/tredegar.nf#L245-L273

**Comment by kapsakcj** [comment]
SeqSero2 if we want to match what EDLB/pulseNet/bionunerics is using

**Comment by kevinlibuit** [comment]
Ah, good call. Leaving this here for reference: [SeqSero2 repo](https://github.com/denglab/SeqSero2) & [StaPH-B dockerfile](https://github.com/StaPH-B/docker-builds/tree/master/seqsero2) 

@kapsakcj do you know how they're using SeqSero2 in BN, i.e. micro-assembly or k-mer workflow?  

```
Usage: SeqSero2_package.py 

-m <string> (which workflow to apply, 'a'(raw reads allele micro-assembly), 'k'(raw reads and genome assembly k-mer), default=a)

-t <string> (input data type, '1' for interleaved paired-end reads, '2' for separated paired-end reads, '3' for single reads, '4' for genome assembly, '5' for nanopore reads (fasta/fastq))

-i <file> (/path/to/input/file)
```

**Comment by kapsakcj** [comment]
Micro-assembly with `-m a`. I just checked with PulseNet.

**Comment by kapsakcj** [comment]
though...with nanopore data, we may want to feed in a polished/final nanopore assembly instead of using the raw nanopore reads. I'm guessing we will hit issues with just using the reads

**Comment by kevinlibuit** [comment]
Added it v0.3.0
