### ISSUE TITLE
Pseudomonas sub-wf for TheiaProk

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bacterial_genomics#118]

**Comment by emmadoughty** [comment]
OM requested wf for _Pseudomonas_ spp, particularly for serotyping. AFAIK, the only serotyping tool is [PAst](https://github.com/Sandramses/PAst), specifically for _P. aeuriginosa_. This will need to be dockerized.

**Comment by emmadoughty** [comment]
Robert has re-written PAst, which is used to identify the serogroup of Pseudomonas aeruginosa isolates. Robert's new implementation is called "[pasty](https://github.com/rpetit3/pasty)" and sounds like this will be easier to use

**Comment by kapsakcj** [comment]
Closed via PR #179
