### ISSUE TITLE
Secondary-species abundance QC

### ISSUE THREAD

**Issue by kevinlibuit** [theiagen/public_health_bacterial_genomics#152]

**Comment by kapsakcj** [comment]
Closed #143 in favor of this issue

MIDAS runs as part of BioNumerics for detecting "secondary species abundance"

requested by a few labs now

https://github.com/snayfach/MIDAS

No staphb docker image, but I think it's on bioconda/biocontainers or alternatively here: https://github.com/FredHutch/docker-midas

If I recall correctly, the database is relatively large and won't be feasible to keep in the docker image

**Comment by kapsakcj** [comment]
addressed via PR #159
