### ISSUE TITLE
ensure WDL compatibility with Azure

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bacterial_genomics#167]
https://github.com/theiagen/public_health_viral_genomics/issues/187

FYI

https://github.com/microsoft/CromwellOnAzure/blob/main/docs/change-existing-WDL-for-Azure.md#How-to-modify-an-existing-WDL-file-to-run-on-Cromwell-on-Azure

**Comment by sage-wright** [comment]
resolved in PHB
