### ISSUE TITLE
Add option for user to specify organism 

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bacterial_genomics#168]
Allow user to specify the merlin tag as an optional wf input and override the GAMBIT prediction for activation of taxa-specific sub-workflows

**Comment by michellescribner** [comment]
Currently I have an "expected_taxon" input for the qc_check task, so when we add this input this is a reminder to make it the expected taxon for the qc_check task too

**Comment by sage-wright** [comment]
resolved in PHB v1.0.1
