### ISSUE TITLE
add seroba outputs to SE

### ISSUE THREAD

**Issue by sage-wright** [theiagen/public_health_bacterial_genomics#193]
They are currently missing

**Comment by kapsakcj** [comment]
I think seroba only supports paired end? Not 100% sure though, it's not clearly stated on the seroba README.md

**Comment by kapsakcj** [comment]
Did we confirm that seroba cannot accept single end illumina data? If so, can we close this issue?

**Comment by sage-wright** [comment]
yes, it's paired-end only i believe.
