### ISSUE TITLE
Request for Neisseria typing

### ISSUE THREAD

**Issue by michellescribner** [theiagen/public_health_bacterial_genomics#205]
Create tasks for https://github.com/MDU-PHL/ngmaster and https://github.com/MDU-PHL/meningotype as in Bactopia?

**Comment by kapsakcj** [comment]
Already have tasks both, though I don't think they are part of the workflows yet though: 

https://github.com/theiagen/public_health_bacterial_genomics/blob/main/tasks/species_typing/task_ngmaster.wdl

https://github.com/theiagen/public_health_bacterial_genomics/blob/main/tasks/species_typing/task_meningotype.wdl

**Comment by michellescribner** [comment]
Ah! I should have looked closer, thank you! Revising request to incorporate them into TheiaProk when we have a chance. I just received an email request about it and believe it has come up previously as well

**Comment by kapsakcj** [comment]
PR #211 will address this. Just posting here for tracking purposes
