### ISSUE TITLE
task_cg_pipeline.wdl: python3 command not found with new lyveset Docker

### ISSUE THREAD

**Issue by sam-baird** [theiagen/public_health_bacterial_genomics#214]
There was an update on 2/15/2023 to the `quay.io/staphb/lyveset:1.1.4f` Docker image. This appears to cause a `python3: command not found` error in `task_cg_pipeline` when I run `wf_theiaprok_illumina_pe.wdl`  v1.1.0 on Terra. I reproduce the command not found error when I pull and run the image on my local machine. I don't get the error on my machine or on Terra when I pull the previous digest of the image: `docker.io/staphb/lyveset@sha256:4ee8d93f22151f26baddf6f569ab63164806b23bbb67bf81625fb137b4825db6`. (I can't pull the previous digest if I use quay.io though, I get a "manifest unkown" error). 

I didn't test it, but maybe calling `python` (v2.7) instead of `python3` could work for what the task is doing.

Thanks for developing this workflow, it's very useful! Just wanted to alert a problem I encountered with a Docker image update.

**Comment by kapsakcj** [comment]
Hi Sam, we appreciate you reporting the issue and apologies that you've hit this error.

We're adding [python3 back to the docker image](https://github.com/StaPH-B/docker-builds/pull/607) and redeploying to dockerhub and quay with the same docker image name & tag as before. Should be available shortly.

As a stop gap solution, you can use the other lyveset docker image we have available for the 2 cg-pipeline tasks, which will resolve the error.

Image name: `staphb/lyveset:2.0.1`

**Comment by kapsakcj** [comment]
Closing this issue as the original lyveset docker image has been updated w/ `python3` and the TheiaProk workflows now run with out error at the cg-pipeline steps.

Please re-open if you are still having issues & thanks again for the bug report!
