### ISSUE TITLE
Kraken2 WDL task/workflow needed

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bacterial_genomics#26]
perhaps with Kalamari database (no container has this database included, yet), perhaps with just minikraken db (container is ready to go).

could potentially host a k2 database on a public bucket, but I would be weary of egress charges....hmmm

**Comment by rpetit3** [comment]
I've added a PE and SE workflows for Kraken2 at https://github.com/theiagen/public_health_bacterial_genomics/tree/rp3-kraken2-dev

**Comment by kapsakcj** [comment]
will be addressed via #70
