### ISSUE TITLE
add BUSCO task?

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bacterial_genomics#42]
https://gitlab.com/ezlab/busco

https://busco.ezlab.org/busco_userguide.html

already have a docker image, but we can add a StaPH-B one 

Requested by one CA county lab and I think this would be a good addition

**Comment by emmadoughty** [comment]
Enhanced QC also requested by OM lab. Either BUSCO or CheckM with the taxonomy wf for Gambit-assigned species would be ideal. CheckM docker image also available (https://hub.docker.com/r/streptomyces/checkm).

**Comment by kapsakcj** [comment]
busco has their own docker image, likely won't need to create one in StaPH-B https://busco.ezlab.org/busco_userguide.html#docker-image
