### ISSUE TITLE
add ncbi-amrfinderplus task for stx gene detection in E. coli

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bacterial_genomics#46]
Can also be used for AMR gene detection for a broad range of organisms too. Database is more curated & up-to-date than abricate

**Comment by rpetit3** [comment]
They just pushed 3.10.24, might be best to start there https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.24 

Had a bug related to a deletion overlapping a mutation

**Comment by kapsakcj** [comment]
staph-b docker image for 3.10.24 incoming: https://github.com/StaPH-B/docker-builds/pull/334

TY for the heads up, Robert

**Comment by kapsakcj** [comment]
@kevinlibuit https://github.com/ncbi/amr/wiki#a-note-about-abricate

**Comment by kevinlibuit** [comment]
@kapsakcj and @rpetit3 this would be great as both a new task that we can add to TheiaProk_Illumina_PE.wdl, but also as a single-task workflow to allow labs to use this tool on any assembly in their workspaces

**Comment by kevinlibuit** [comment]
Also a request from PHLs to organize final outputs into element-type tsvs, e.g. one for AMR, one for virulence, and a third for stress

**Comment by kapsakcj** [comment]
Started a dev branch for this [cjk-amrfinderplus-dev](https://github.com/theiagen/public_health_bacterial_genomics/tree/cjk-amrfinderplus-dev)

added a task for basic usage of amrfinderplus. the WDL passes `miniwdl check` but has not been incorporated into any workflows yet

**Comment by kapsakcj** [comment]
Got a new single-task workflow `NCBI-AMRFinderPlus` running successfully in Terra 🎉 

https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/curtis_sandbox/data
