### ISSUE TITLE
add genotyphi to theiaprok_illumina_pe wf

### ISSUE THREAD

**Issue by kapsakcj** [theiagen/public_health_bacterial_genomics#92]
Started a branch `cjk-genotyphi` to get this started

Planning to only run `genotyphi` on samples where either SeqSero2 or SISTR find a serotype of Typhi

This will use the soon-to-be-released staphb docker image for `mykrobe` and `genotyphi`

See here for usage of the tool: https://github.com/StaPH-B/docker-builds/blob/4267433bee23ac5ca6c8cb0f818a48a7e6507c22/mykrobe/README.md

2 steps - run Mykrobe to produce, then parse outputs w/ genotyphi script to produce a TSV.

Things to float to Terra table as outputs:

- mykrobe output JSON
- genotyphi TSV
- genotyphi final predicted lineage
- others?!?

**Comment by kevinlibuit** [comment]
@kapsakcj ready for PR?
