### ISSUE TITLE
Acinetobacter baumannii sub-workflow

### ISSUE THREAD

**Issue by emmadoughty** [theiagen/public_health_bacterial_genomics#99]
Request from OM collaborators:
Create an Acinetobacter baumannii-specific taxon table and trigger 1) Kaptive to run on those samples for A. baumannii K/OC typing, 2) Torsten's MLST to process those samples using the Oxford scheme (in addition to Pasteur scheme).

Kaptive is available in Docker already (https://github.com/StaPH-B/docker-builds/tree/master/kaptive/2.0.3)

**Comment by emmadoughty** [comment]
It may be valuable to confirm that samples passed to this sub-workflow are "true" Acinetobacter baumannii by BLASTing for the presence of the oxaAB gene

**Comment by kapsakcj** [comment]
partially addressed via #138 with regards to starting a sub-workflow with `kaptive` for K and O typing.

We should discuss the plan for next steps
